name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore AdminDashboard.Api.sln
      - name: Build
        run: dotnet build AdminDashboard.Api.sln --no-restore --configuration Release
      - name: Test
        run: dotnet test AdminDashboard.Api.Tests/AdminDashboard.Api.Tests.csproj --no-build --logger "console;verbosity=detailed" 